### ISSUE TITLE
shallowEqual() should handle NaN values correctly

### ISSUE THREAD

**Issue by rickbeerendonk** [facebook/fbjs#101]
shallowEqual() should return true when dealing with NaN.

```
shallowEqual(NaN, NaN);  // true
shallowEqual({a: NaN}, {a: NaN});  // true
```

Fixing this would also fix the confusing error in React, see [React Issue 5773](https://github.com/facebook/react/issues/5773).

**Comment by zpao** [comment]
As mentioned, will be syncing this out from internal at some point, but yes, we will be doing this.
