### ISSUE TITLE
reletavise requires in compiled .flow files

### ISSUE THREAD

**Issue by zpao** [facebook/fbjs#118]
There's an issue right now where the result is that we basically force all indirect consumers of fbjs (eg using Relay) to use the haste system in their package or ignore things specifically. @mroch said we should be able to make this work with our projects and others by rewriting the requires in our generated flow files so they are relative while keeping the `@providesModule` headers.

**Comment by samwgoldman** [comment]
mine

**Comment by zpao** [comment]
👍 we might need to upgrade Babel for this to work, at least the plan I had
was to just run through Babel with only the existing requires pouring we
use for js. But that's not possible right now to run through and only do
that with Babel 5 (at least in the 2 minutes I tried)

**Comment by samwgoldman** [comment]
Thanks—pretty eager to get this fix out. Does a Babel upgrade have any blockers to landing, other than just getting it to work locally?

**Comment by zpao** [comment]
I think the only thing I'd check is diff the JS files before and after to make sure we don't slip anything in there we don't expect. We have all the plugins ported already. And actually we're just about to do the upgrade for React in https://github.com/facebook/react/pull/6113

**Comment by kittens** [comment]
Do we have anything else that uses Babel 5? I want to kill it with fire.

**Comment by samwgoldman** [comment]
@kittens If you're on a tear and want to take this one, go for it. I think you'll be able to turn it around faster than me. :)

**Comment by zpao** [comment]
Literally everything else besides React Native still uses 5.

**Comment by kittens** [comment]
Like what? React Native, Relay, www, and now React all use Babel 6.

**Comment by zpao** [comment]
Relay doesn't use Babel 6, nor does flux nor draft. Nothing using
fbjs-scripts did until today (all need the dev plugin you just wrote)

**Comment by kittens** [comment]
Thanks for the list, I'll upgrade all of those next week..

On Saturday, 27 February 2016, Paul O’Shannessy <notifications@github.com>
wrote:

> Relay doesn't use Babel 6, nor does flux nor draft. Nothing using
> fbjs-scripts did until today (all need the dev plugin you just wrote)
>
> On Friday, February 26, 2016, Sebastian McKenzie <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Like what? React Native, Relay, www, and now React all use Babel 6.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/facebook/fbjs/issues/118#issuecomment-189577574>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/fbjs/issues/118#issuecomment-189599897>.
>


-- 
Sebastian McKenzie
