### ISSUE TITLE
Increase Requirement to Node v4

### ISSUE THREAD

**Issue by yungsters** [facebook/fbjs#128]
What is holding us back from increasing the node version requirement to v4? This will allow us to use a lot of niceties like arrow functions, concise object notation, `Object.assign`, etc.

**Comment by zpao** [comment]
![make-it-so-captain](https://cloud.githubusercontent.com/assets/8445/13696326/8388e9da-e71a-11e5-90b8-32c205261ca1.jpg)

(I was already working off the assumption 4 was what we all used)
