### ISSUE TITLE
the eslint stay in 1.x , could modified it to 2.x?

### ISSUE THREAD

**Issue by iamchenxin** [facebook/fbjs#131]
Seems modified the fbjs-scripts's `.eslintrc.js`'s 1.x rules to 2.x , all eslint rules still work correctly.
Is staying in 1.x because of compatibility for jshint ? ( i known nothing about jshint,just guess).

**Comment by zpao** [comment]
Simply compatibility with our internal setup. I'm the only one doing this upgrade and haven't had a chance to make sure all of our internal rules and config that isn't synced out is still ok.

**Comment by iamchenxin** [comment]
@zpao  Thank you! so i could fork and modified,then use these with eslint 2.x, seems these are no implicitly problem with new project.

**Comment by zpao** [comment]
Just updated our config for eslint 2 in #140, will ship in the next fbjs-scripts.

**Comment by iamchenxin** [comment]
@zpao Its awesome :+1:  :D
