### ISSUE TITLE
0.8.0 break some project

### ISSUE THREAD

**Issue by Freddy03h** [facebook/fbjs#133]
## Issue
Hello, I created a project using a starter kit https://github.com/davezuko/react-redux-starter-kit, and by default, after an `npm install` it use fbjs@0.6.0.
Later, I installed draft-js and it use fbjs@0.8.0-alpha2, and since, I can't run test on my project anymore (karma, phantomjs, chai, etc).

I've got the following error :
```
START:
06 04 2016 17:53:21.039:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
06 04 2016 17:53:21.071:INFO [launcher]: Starting browser PhantomJS
06 04 2016 17:53:22.960:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#gba2WCoQqyELMJKhAAAA with id 86581400
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  TypeError: undefined is not a constructor (evaluating 'query.startsWith(name)')
  at /Users/freddy/Desktop/react-redux-starter-kit/tests/test-bundler.js:91609 <- webpack:///~/draft-js/~/fbjs/lib/UserAgent.js:35:0

Finished in 0.654 secs / 0 secs

SUMMARY:
✔ 0 tests completed
```
## More information
I also opened an issue on the starter-kit project : https://github.com/davezuko/react-redux-starter-kit/issues/697
and **How to Reproduce**

## related ?
I don't know if it's an issue related to this project, or directly related to the starter-kit or maybe phantomjs. So, sorry if it's not related to this project.

**Comment by zpao** [comment]
Is the fbjs in there 0.8.0-alpha.2 or 0.8.0? Not much should have changed between.

**Comment by Freddy03h** [comment]
It's the alpha.2, I renamed the issue.
It's the version used by draft-js https://github.com/facebook/draft-js/blob/master/package.json#L32 and react@15.0.0-rc.2 https://github.com/facebook/react/blob/master/package.json#L38

I don't have the same issue by upgrading react and react-dom to this version on my project (and without draft-js). Maybe it's because react(-dom) don't use `fbjs/lib/UserAgent` ?

**Comment by Freddy03h** [comment]
Hum, I also tried with fbjs@0.8.0 and still have the same issue using draft-js

**Comment by zpao** [comment]
Ah, I think this is a polyfill related issue. `query.startsWith(name)` is expecting `String.prototype.startsWith` to exist. This is a new method in ES6 ([MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith)). Especially in Phantom, even new Phantom, you're going to need to include a polyfill for some of these things. The same holds true in real browser environments.

See the note in the docs: https://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#polyfills In the future we might compile that away and ship with a polyfill (or inline method) ourselves but for the time being, we're going to just depend on the method existing.

Let me know if that doesn't work and we can reopen and reinvestigate.

**Comment by zpao** [comment]
PS, thanks for the awesomely detailed report including a repro and (what you could get of a) stack trace.

**Comment by Freddy03h** [comment]
Oh, ok I understand !
I fix the issue by adding `babel-polyfill` to the `karma.conf.js` file.

Thank you for your help and yours quicks answers !
