### ISSUE TITLE
Put old 'object.assign' modules here? 

### ISSUE THREAD

**Issue by ev1stensberg** [facebook/fbjs#134]
#  React: 

In v15 the internal module file `object.assign.js` got swapped, as you probably know. Should we consider to put it in here for people to use? I know it's double up, since it's doing the same as the npm package, but some libraries depend on the old `Object.assign`. I believe the old `Object.assign` also was deeply used in the previous versions, so this would not matter for some libraries, as they would depend on those deep nested assigns as well as only the module file.

This won't solve all problems though, but it would be a nice add to smoothen the transition between v.15 and previous versions of React for extension libraries such as React-Canvas (which just got super-outdated)

**Comment by spicyj** [comment]
In general we don't support other libraries using our internal modules. This can suck and means that we break stuff but we wouldn't be able to get anything done if we never moved stuff around internally. As a result, I'm inclined to say that we won't do this. However, I don't quite understand the ask – why is it easier to change to `require('fbjs/lib/Object.assign')` than to `require('object-assign')`?

**Comment by ev1stensberg** [comment]
Libraries such as React Canvas used Object.assign to mount their components to react, if I understood the code correctly!
