### ISSUE TITLE
Dependency to core-js prevents commit to TFS source control

### ISSUE THREAD

**Issue by Strato** [facebook/fbjs#138]
Hello,

A couple of months ago we TFS users have encountered a [problem](https://github.com/zloirock/core-js/issues/129) with core-js. The core-js package was containing some files wth a dollar sign ($) which is not allowed in TFS source control.

This was fixed in core-js 2.0.0 which was released on 12-24-2015.

Problem is... fbjs is still using core-js 1.2.6, and this prevents us from commiting our node_modules directory to TFS. Actually we're using React which references fbjs.

+-- react@15.0.1
| +-- fbjs@0.8.1
| | +-- babel-plugin-syntax-flow@6.5.0
| | | `-- babel-runtime@5.8.38
| | +-- core-js@1.2.6
| | +-- isomorphic-fetch@2.2.1
| | | `-- node-fetch@1.5.1
| | |   +-- encoding@0.1.12
| | |   | `-- iconv-lite@0.4.13
| | |   `-- is-stream@1.1.0
| | +-- promise@7.1.1
| | | `-- asap@2.0.3
| | `-- ua-parser-js@0.7.10
| `-- loose-envify@1.1.0
|   `-- js-tokens@1.0.3

So do you have plans, in a not too distant future, to switch to core-js 2?

To be honest I'm not a super specialist of NPM. Do you know if, in the interval, there's a way I could force fbjs to use last core-js version?

**Comment by zpao** [comment]
Sorry about that, I haven't had a chance to look into what the difference is in core-js 1 vs 2, so have left it unupgraded for now.

> Do you know if, in the interval, there's a way I could force fbjs to use last core-js version?

Assuming you are using npm2 then you could `cd node_modules/react/node_modules/fbjs; rm -rf node_modules/core-js; npm install core-js@latest`

**Comment by Strato** [comment]
Thanks for your help.

We're using Node 5/NPM 3, but I ended up using [NPM-ShrinkWrap](http://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions), with this file:

```
{
  "name": "some-project",
  "version": "0.0.1",
  "dependencies": {
    "babel-runtime": {
      "version": "5.8.38",
      "from": "babel-runtime@>=5.0.0 <6.0.0",
      "dependencies": {
        "core-js": {
          "version": "2.3.0",
          "from": "core-js@>=1.0.0 <2.0.0"
        }
      }
    },
    "fbjs": {
      "version": "0.8.1",
      "from": "fbjs@>=0.8.0 <0.9.0",
      "dependencies": {
        "core-js": {
            "version": "2.3.0",
            "from": "core-js@>=1.0.0 <2.0.0"
        }
      }
    }
  }
}
```

It worked flawflessly. Well... WebPack didn't complain and React works so I suppose it does work.

Bumping core-js in your library should be easy too.
