### ISSUE TITLE
Remove "Failed Composite propType" checking from `warning`

### ISSUE THREAD

**Issue by keyanzhang** [facebook/fbjs#152]
facebook/react#6824 removed duplicate propType checking, therefore the blacklist at https://github.com/facebook/fbjs/blob/master/src/__forks__/warning.js#L34-L36 is no longer necessary. Should we remove it from here? @spicyj

**Comment by spicyj** [comment]
Yes, I mentioned that in https://github.com/facebook/react/issues/6791. :) Send a PR?
