### ISSUE TITLE
Create a README file

### ISSUE THREAD

**Issue by KrishMunot** [facebook/fbjs#169]

**Comment by Daniel15** [comment]
The readme at https://github.com/facebook/fbjs/blob/master/packages/fbjs/README.md is pretty good - We should probably move that to the root and symlink it to `packages/fbjs/README.md` for the npm package.

**Comment by KrishMunot** [comment]
@Daniel15 : Just made the changes appropriately and added the README.md file to the root. Refer https://github.com/facebook/fbjs/pull/172

**Comment by KrishMunot** [comment]
Closing this issue, as https://github.com/facebook/fbjs/pull/172 is solving it.
