### ISSUE TITLE
^0.8.3 includes immutable

### ISSUE THREAD

**Issue by Cap32** [facebook/fbjs#170]
I'm not a big fan of `immutable.js`, because it is too big (the latest `immutable.min.js` is 55.7 KB without gzip).

`React ^v15.0` depends on `fbjs ^v0.8`, so `npm` will install `fbjs@v0.8.3` by default.

Does it mean React is now depends on immutable.js now??? I hadn't found any documents mention this.

**Comment by gaearon** [comment]
No, React doesn’t import any module that depends on Immutable from fbjs.
Just because it gets installed with fbjs, doesn’t mean React will import it.
You can check by bundling your app—you won’t find Immutable in it. 😉

**Comment by Cap32** [comment]
Thanks for your reply 👍🏿

**Comment by just-boris** [comment]
Hello!
Today I was investigating why do I have immutable installed, even though I don't have it in dependency. I have figured out that it comes from `fbjs` which is React dependency.

Is there any chance to split up the library and include into React dependency only that part which doesn't require `immutable`?

I understand that it will not be included in the bundle anyway, but install and build time is also matters.

**Comment by zpao** [comment]
It's 1 extra small dependency, which won't break the bank. I understand the concern but we won't be doing anything about it at this time.
