### ISSUE TITLE
Provide some kind of guidance for using haste system with webpack

### ISSUE THREAD

**Issue by barbu110** [facebook/fbjs#178]
I am aware of the description of the repo, *those who use this will have a hard time*, but I would be grateful if somebody would give a couple of minutes to explain me (and probably others) how to use the Haste module system with webpack.

So I see it's quite simple to use it with gulp, basically, you just generate the modules map and use the Babel API to rewrite the `require`s, essentially skiping the `.babelrc`. 

1. But how should I do this in a webpack environment?
2. When should I generate the modules map?

Thank you!

**Comment by zpao** [comment]
You're welcome to figure that out on your own but as this is a system designed specifically for us to use and it works - we're not going to invest resources in figuring something else out right now. We compile to commonjs for npm for everybody (including us) to use.

Sorry that's not a great answer but we just don't have the time to figure spend on this.

**Comment by barbu110** [comment]
It would take as much as 5 minutes for someone like you (who this software even in the middle of night) to write a piece of code that would run

**Comment by zpao** [comment]
I appreciate that you think so highly of me but it would take longer than 5 minutes for sure. I don't know how webpack works and would need to figure out how to inject a module resolver. And then I would need to find every file on disk and read it to get the providesModule declaration and build a map, assuming that's even how webpack works.

I have no need to do this so I won't be spending any more time on the matter. Good luck.

**Comment by jrwm** [comment]
@barbu110 Have you resolved it on your own? I am very interested in a solution ;)
