### ISSUE TITLE
AssertionError: Current npm version is not supported for development, expected "4.0.2" to satisfy "2.x || 3.x".

### ISSUE THREAD

**Issue by crowdwave** [facebook/fbjs#197]
Can't find a way around this.

I've tried everything from upgrading to node 6 and downgrading again and upgrading npm but still no luck.  

I've deleted my node_modules and done npm install but same problem.

Can anyone suggest what is wrong please and more important how to fix it?

thanks

155694 info lifecycle bootrino@0.1.0~postinstall: Failed to exec postinstall script
155695 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
155696 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current:
 {"os":"win32","arch":"x64"})
155697 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
155697 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
155697 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
155697 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155698 warn optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-linux@^1.0.3 (node_modules\7zip-bin\node_modules\7zip-bin-linux):
155699 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-linux@1.0.3: wanted {"os":"linux","arch":"any"} (curr
ent: {"os":"win32","arch":"x64"})
155700 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    linux
155700 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
155700 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
155700 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155701 warn optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@^1.0.1 (node_modules\7zip-bin\node_modules\7zip-bin-mac):
155702 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (curre
nt: {"os":"win32","arch":"x64"})
155703 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
155703 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
155703 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
155703 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
155704 warn eslint-config-airbnb@13.0.0 requires a peer of eslint-plugin-jsx-a11y@^2.2.3 but none was installed.
155705 verbose If you need help, you may report this error at:
155705 verbose     <https://github.com/npm/npm/issues>
155706 warn bootrino@0.1.0 No repository field.
155707 verbose If you need help, you may report this error at:
155707 verbose     <https://github.com/npm/npm/issues>
155708 warn bootrino@0.1.0 No license field.
155709 verbose If you need help, you may report this error at:
155709 verbose     <https://github.com/npm/npm/issues>
155710 verbose stack Error: bootrino@0.1.0 postinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
155710 verbose stack Exit status 1
155710 verbose stack     at EventEmitter.<anonymous> (C:\Users\x\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:
279:16)
155710 verbose stack     at emitTwo (events.js:87:13)
155710 verbose stack     at EventEmitter.emit (events.js:172:7)
155710 verbose stack     at ChildProcess.<anonymous> (C:\Users\x\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:1
4)
155710 verbose stack     at emitTwo (events.js:87:13)
155710 verbose stack     at ChildProcess.emit (events.js:172:7)
155710 verbose stack     at maybeClose (internal/child_process.js:854:16)
155710 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
155711 verbose pkgid bootrino@0.1.0
155712 verbose cwd C:\Users\x\devel\unikerneldesktopnew
155713 error Windows_NT 10.0.14393
155714 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\x\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli
.js" "install"
155715 error node v4.6.2
155716 error npm  v4.0.2
155717 error code ELIFECYCLE
155718 error bootrino@0.1.0 postinstall: `node node_modules/fbjs-scripts/node/check-dev-engines.js package.json`
155718 error Exit status 1
155719 error Failed at the bootrino@0.1.0 postinstall script 'node node_modules/fbjs-scripts/node/check-dev-engines.js package.json'.
155719 error Make sure you have the latest version of node.js and npm installed.
155719 error If you do, this is most likely a problem with the bootrino package,
155719 error not with npm itself.
155719 error Tell the author that this fails on your system:
155719 error     node node_modules/fbjs-scripts/node/check-dev-engines.js package.json
155719 error You can get information on how to open an issue for this project with:
155719 error     npm bugs bootrino
155719 error Or if that isn't available, you can get their info via:
155719 error     npm owner ls bootrino
155719 error There is likely additional logging output above.
155720 verbose exit [ 1, true ]
PS C:\Users\x\devel\unikerneldesktopnew>

**Comment by zpao** [comment]
Looking at that log, bootrino is using a script we ship to check its own
devDependencies. However it does it in a postinstall hook which is the
wrong place to do it (since post install will get run when installing the
package not just for local package development).

This isn't an issue with us and you should file against their repo.
