### ISSUE TITLE
IE Regression - createArrayFromMixed was changed to Array.from 

### ISSUE THREAD

**Issue by dekelcohen** [facebook/fbjs#198]
Hi,

We use React 0.14.8 which depends on fbjs ^0.6.1  - these versions were working for us also in IE (at least IE 11).

commit 064a484 in createNodesFromMarkup.js changed createArrayFromMixed --> Array.from --> Fails to load our app in IE (which never supported Array.from). It was published in fbjs 0.8.x --> therefore react npm dependencies were updated to it automatically (^0.6.1).

Note that another call to createArrayFromMixed (2 lines above) was not changed.

Workaround:
Use Array.from polyfill 

Solutions:
1) Is it possible to revert back to using createArrayFromMixed ?
2) If not, do you intend to use Babel polyfills ? They include Array.from

Let me know if a pull request is needed.

**Comment by zpao** [comment]
`^0.6.1` won't update to `0.8.x` (caret range won't update minor version when major version is 0), though there's a chance you have something else in your app using a newer fbjs which could result in bundling issues.

This was done in as safe a way as possible (across versions) so it's unlikely we'll take any fixes here. I would recommend just ensuring that you have an Array.from polyfill - we don't intend on shipping our own here.
