### ISSUE TITLE
Please move eslint-preset-fbjs peerDependencies to dependencies

### ISSUE THREAD

**Issue by joefitzgerald** [facebook/fbjs#211]
https://github.com/facebook/fbjs/blob/9b1198d7a6eb71fcd9f1d4b373ec473f2c88c34e/packages/eslint-config-fbjs/package.json#L22-L30

### Rationale

Managing the versions of the various peerDependencies is unnecessary; if you need the dependencies installed, please include them as dependencies so they are installed transitively. If some peerDependencies are not required, then please remove them completely.

**Comment by zpao** [comment]
Closing because we'll tackle this differently. See #212
