### ISSUE TITLE
Create eslint-config-fbjs-opensource

### ISSUE THREAD

**Issue by zpao** [facebook/fbjs#212]
The current situation of peerDeps and `fbjs/opensource` config isn't acceptable for people so we should just make an entirely separate package.

It's worth noting that this will be a deviation from apparent best practices of eslint config packages - it seems they all have peerDeps and installation requires installing multiple packages.

Potential issues:
- I'm not sure what happens if the parent package also has a non-compatible plugin package installed (Eg eslint-plugin-react 5 vs 6). Eslint does the requires from the node_modules root so I'm guessing the topmost package will get used which could lead to some unexpected behavior. We'll just have to make it clear that this package is intended to be used as the only eslint-related package and may have incompatibilities with other plugins.

**Comment by nathansobo** [comment]
I'm curious how the `standard` package deals with these issues. Maybe it just isn't customizable as you've described.

**Comment by zpao** [comment]
`standard` follows the common practice of using peerDeps for plugins, so isn't at risk for the same issue.

> To use the JavaScript Standard Style shareable config, first run this:
> `npm install --save-dev eslint-config-standard eslint-plugin-standard eslint-plugin-promise`

**Comment by zpao** [comment]
https://www.npmjs.com/package/eslint-config-fbjs-opensource is published. Go wild.
