### ISSUE TITLE
Release 0.9.0 (non-alpha version)

### ISSUE THREAD

**Issue by dmnd** [facebook/fbjs#217]
Relay is currently depending on 0.8.1 because 0.9.0 is still in alpha (and has been for 7 months).

This is a problem for Relay because it ends up depending on core-js twice (see https://github.com/facebook/relay/issues/1421).

Can you please publish the current alpha as a real release?

**Comment by zpao** [comment]
React 15.x probably won't upgrade past fbjs 0.8.x so you won't see the benefits you're looking for in that other issue. I'll have to go back and see what has changed but I'm pretty sure there was a big difference with shallowCompare that would require React doing a major bump.

As to @wincent's question about why there's even an alpha here… I think that was to get some code into the hands of Draft, and then I haven't done a sync in a months.

We can do a sync here and land a couple other things (#165 should probably ship), but like I said, you likely won't see the benefits you want yet. Maybe we could update core-js in the 0.8 branch.

**Comment by dmnd** [comment]
Releasing a non-alpha would still set things up to work nicely once React 16 ships, assuming they also bump to 0.9.0. 16 is already a major change so probably they'd be ok with updating fbjs too?

> Maybe we could update core-js in the 0.8 branch.

That'd be nice in the meantime if you're up for it.

**Comment by dmnd** [comment]
Closing since releases happened. Thanks!
