### ISSUE TITLE
Assignment to read-only properties is not allowed in strict mode / IE11

### ISSUE THREAD

**Issue by brianthiel** [facebook/fbjs#220]
I am getting this error in Windows 10 / IE11. Can't seem to resolve the issue. The error traces back to the CSSCore module.

Dependency versions:

    "babel-runtime": "6.23.0",
    "gsap": "1.19.1",
    "meteor-node-stubs": "0.2.5",
    "react": "15.4.2",
    "react-addons-css-transition-group": "15.4.2",
    "react-dom": "15.4.2",
    "react-helmet": "4.0.0",
    "react-lazyload": "2.2.3",
    "react-router": "3.0.2",
    "react-waypoint": "5.1.0"

![ie11-error](https://cloud.githubusercontent.com/assets/9473024/22996461/7df7fc2c-f394-11e6-9a9b-754cfdfd6f38.png)

![ie11-error-detail](https://cloud.githubusercontent.com/assets/9473024/22996460/7df6972e-f394-11e6-9d39-3064c4e17a98.png)

**Comment by brianthiel** [comment]
Only seems to be an issue in IE11. Not getting error in current releases of Edge, Chrome, Firefox or Safari.

**Comment by zpao** [comment]
What is `element` there?

It would be great if you could make a test case. We haven't had any issues with this so I suspect it's an edge case we haven't hit but you are. Without more info, it'll be really tough to find.

**Comment by brianthiel** [comment]
Not 100% sure what `element` is in that instance. This error was coming from the compiled JS being bundled by meteor. 

After testing and debugging and testing, I was able to solve the issue by removing react-addons-css-transition-group package. I assume now it must of been something about how I was using that package.

**Comment by zpao** [comment]
Alright, I'm just going to close this out then if we can't repo. My best guess is actually that there's a hard to hit bug in transition-group, trying to do a DOM operation after unmounting. Thanks for filing and let us know if you find a shareable repro.
