### ISSUE TITLE
Sorry for unrelated but i am looking for source code of https://connect.facebook.net/en_US/sdk.js

### ISSUE THREAD

**Issue by v3ss0n** [facebook/fbjs#221]
Is Facebook JS SDK Opensource? I read the license as Apache , would be nice if the non-minified source code  released as opensource too.
https://connect.facebook.net/en_US/sdk.js
- Motivation
Facebook JS SDK in webview is a pain when crosswalk is added . A simple fix to window.open will work fine but since only minifed script exists , its hard to do.

**Comment by zpao** [comment]
Sorry don't know anything about that. Best bet is to go through https://developers.facebook.com/bugs/
