### ISSUE TITLE
npm'd version fails flow

### ISSUE THREAD

**Issue by jaredly** [facebook/fbjs#23]
The transpiled version has stuff like:

```js
function Deferred /*:: <Tvalue, Treason>*/() {
  // stuff ...
}

Deferred.prototype.resolve = function resolve(value /*: Tvalue*/) /*: void*/ {
  this._settled = true;
  this._resolve(value);
};
```

Which makes `Tvalue` undefined, b/c it's not in the same scope.
Not sure if this is a flow bug or not, but it makes it so I can't use this lib :(

**Comment by jaredly** [comment]
Maybe a reasonable fix would be to include the un-transpiled code as well in the npm version, so that flow/babel-using clients can use the original stuff.

**Comment by zpao** [comment]
KP that we're working through. See #17. cc @yungsters

Including the uncompiled code was discussed but module resolution gets tricky. It's doable but a bit messy.

**Comment by yungsters** [comment]
Until Flow Comments is more stable, figuring out a solution involving packaging the un-transpiled code seems like a good idea. GraphQL is also running into this right now.

cc @dschafer @leebyron

**Comment by leebyron** [comment]
As of v0.2.0, GraphQL-js is now using https://github.com/babel-plugins/babel-plugin-flow-comments
