### ISSUE TITLE
Add repository entry in fbjs-css-vars/package.json for WebJars compatibility

### ISSUE THREAD

**Issue by kaqqao** [facebook/fbjs#248]
[WebJars](https://www.webjars.org/) packages NPM libraries as .jars for consumption in the JVM.
fbjs-css-vars seems to break due to the missing `repository` entry in its `package.json`.

**Comment by joost-de-vries** [comment]
👍

**Comment by zpao** [comment]
WebJars should probably be fixed such that it doesn't require that field to exist as it isn't a requirement for npm packages. I encourage you to try to get that fixed.

In the meantime, I'll publish a new version with it set.

**Comment by zpao** [comment]
v1.0.1 is published with this fixed.

**Comment by joost-de-vries** [comment]
Cool. Tx!

**Comment by kaqqao** [comment]
@zpao I think they did do something about it recently. Thanks a bunch for the fix!
