### ISSUE TITLE
JetBrains - Code Style import 

### ISSUE THREAD

**Issue by sm2017** [facebook/fbjs#251]
How can I import fbjs code style to WebStorm  ? 
I use `Code -> Reformat Code` frequency and currently it is not compatible with fbjs

**Comment by zpao** [comment]
Are you working on something in `fbjs`? I don't use WebStorm nor that feature so I'm not sure I can help here.

**Comment by sm2017** [comment]
@zpao I want to build a project with react native , and want to match with facebook code style

Is Atom IDE (with Nuclide) has `Reformat Code` and format my code using `.eslintrc` file ?

**Comment by sm2017** [comment]
@zpao Can you help me?

**Comment by zpao** [comment]
You can use the published eslint config if JetBrains supports that. Nuclide's reformat code uses prettier, so you can just use that.

Otherwise, I don't think there's anything else I can do to help you.
