### ISSUE TITLE
Jest test fails because onChange is missing but have onClick here

### ISSUE THREAD

**Issue by binarykitchen** [facebook/fbjs#283]
Seeing this warning when running jest tests:

```
    console.error node_modules/fbjs/lib/warning.js:33
      Warning: Failed form propType: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
```

Having this cjsx code here

```cjsx
          <input
            checked = {@_isAllSelected()}
            type = "checkbox"
            name = "selectAll"
            onClick = {@_onSelectAll}
          />
```

Has to be onClick for app specific purposes which works fine as if it were onChange. Yet fbjs warns it should be onChange.

Can this be improved, not to warn when onClick is detected as well?

**Comment by zpao** [comment]
This warning doesn't come from fbjs, it's coming from React (which uses fbjs).

**Comment by binarykitchen** [comment]
done, reported it here https://github.com/facebook/react/issues/12338
