### ISSUE TITLE
Possible license violation (ua-parser-js)

### ISSUE THREAD

**Issue by grgur** [facebook/fbjs#296]
[ua-parser-js](https://github.com/faisalman/ua-parser-js) is dual licensed GPLv2 + MIT. This may require `fbjs` (and `react`) to update the license accordingly

**Comment by grgur** [comment]
`ua-parser-js` has changed from `GPLv2 & MIT` to `GPLv2 or MIT`. AFAIK this is no longer an issue. Closing

**Comment by zpao** [comment]
Yea, that was definitely a typo. It's not possible to dual license with an "and" :) Thanks for the vigilance!

**Comment by natac13** [comment]
I see this issue is closed, however could I submit a pull request to bump the version of `ua-parser-js` to 0.7.20 which was relicensed with just MIT
 https://github.com/facebook/fbjs/blob/35d7693c0908820af5a0ed2635dbae45ab6feeb8/packages/fbjs/package.json#L74
