### ISSUE TITLE
fbjs-css-vars - please update in npm

### ISSUE THREAD

**Issue by mimiempi** [facebook/fbjs#326]
Hi,
Some time ago fbjs package changed license from Facebook BSD License with Patent Provision to MIT. In our project we are using npm to download and resolve dependencies. However lately we have found our that our software still using the old license because the package still is not updated in npm storage. 
https://www.npmjs.com/package/fbjs-css-vars
This might cause real problems for commercial software. 
Could you please upgrade the version that is provided by npm, so it would contain the proper, MIT, license.
Thanks.

**Comment by zpao** [comment]
Just published. Thanks for the reminder.
