### ISSUE TITLE
outdated dependency

### ISSUE THREAD

**Issue by rick-software** [facebook/fbjs#349]
fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

npm ls core-js
my-app@0.1.0 /Users/rick/develpment/app/client
├─┬ react-scripts@3.0.1
│ ├─┬ react-app-polyfill@1.0.1
│ │ └── core-js@3.0.1 
│ └─┬ workbox-webpack-plugin@4.2.0
│   └─┬ workbox-build@4.3.1
│     └─┬ strip-comments@1.0.2
│       └─┬ babel-plugin-transform-object-rest-spread@6.26.0
│         └─┬ babel-runtime@6.26.0
│           └── core-js@2.6.9 
└─┬ recompose@0.30.0
  └─┬ fbjs@0.8.17
    └── core-js@1.2.7 

Please upgrade this dependency

**Comment by rhberro** [comment]
Is going to be fixed? looking forward to a reply.

**Comment by bensampaio** [comment]
Same here

**Comment by mschipperheyn** [comment]
Yeah guys, this is ancient code. And is creating problems.

**Comment by evanrlong** [comment]
I would also like to see this fixed.

**Comment by fasaas** [comment]
It's actually blocking my component development, where npm is deciding to install core-js version 1 because of this package whereas every other package (say babel for instance) has a dependency on 2.7 or above

**Comment by fasaas** [comment]
I can't believe that moving over to yarn instead of npm unblocked me. However, I am not sure of the side effects of this move

**Comment by silkfire** [comment]
@zpao When can this be released?

**Comment by vadavallipavan** [comment]
React Native is dependent on version 1.0.0 and it uses old Core-js and warning keeps coming - Any response here from the maintainers is appreciated.

**Comment by castlewu9** [comment]
same here

**Comment by jdeff** [comment]
It looks like #370 has been merged. Any idea when we can get a release for the fbjs-scripts?

**Comment by bateau** [comment]
@zpao When are you guys expected to release updated fbjs version which fixes the dependency warning?  My project is consuming draft-js and also getting `fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained.` warning.

**Comment by zpao** [comment]
2.0.0 has been published.

**Comment by yungsters** [comment]
@vadavallipavan, the next release of `react-native` will no longer have a dependency on `fbjs`.
