### ISSUE TITLE
Add TypeScript definitions

### ISSUE THREAD

**Issue by fandy** [facebook/fbjs#350]
Would be great to add to DefinitelyTyped so it can be used in a TS project.

**Comment by wKich** [comment]
Any progress?

**Comment by zpao** [comment]
We aren't going to do this but anybody is welcome to submit definitions. To be clear, you should almost certainly not be using this package in your own code, as mentioned in the readme:

> *Note:* If you are consuming the code here and you are not also a Facebook project, be prepared for a bad time.
