### ISSUE TITLE
ITMS-90809: Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by arthedza** [facebook/fbjs#362]
I checked up my node_modules and found that this module referenced deprecated UIWebView
https://developer.apple.com/documentation/uikit/uiwebview

**Comment by zpao** [comment]
This is just because a dependency. Should be fine though, it's just checking user agent strings which might still be relevant for old clients.

**Comment by upcwangying** [comment]
@zpao I run the command `grep -r UIWebView node_modules/* > wv.txt` and I get the following information. 

```
node_modules/create-react-class/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/create-react-class/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
node_modules/jsc-android/dist/include/JSContextPrivate.h:/*! @abstract The delegate the context will use when trying to load a module. Note, this delegate will be ignored for contexts returned by UIWebView. */
node_modules/react-native-webview/README.md:- [7.0.1](https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1) - Removed UIWebView
node_modules/ua-parser-js/test/browser-test.json:        "ua"      : "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A456 QQ/6.5.3.410 V1_IPH_SQ_6.5.3_1_APP_A Pixel/1080 Core/UIWebView NetType/WIFI Mem/26",

```

**Comment by aikewoody** [comment]
@upcwangying @arthedza 

The same search also brought me here, if you look into the files (`UserAgent.js.flow` and `UserAgent.js`) where the string `UIWebView` occurs there is no need to worry. There is just a single line where it is used and that exact line is the following: `   * - UIWebView`

It's just a comment in the source code, the native view is not used in any way and can't be the cause of the `ITMS-90809: Deprecated API Usage UIWebView` problem.
