### ISSUE TITLE
New gTLDs , IDNs, EAI and Linkification issues

### ISSUE THREAD

**Issue by UA2018** [facebook/fbjs#368]
Many top-level domains (TLD), such as .technology, family, .gay  are missing from Facebook's library.

We come across universal acceptance issues when trying to create an account with Unicode emails (email address internationalization), such as 测试5@普遍接受-测试.世界.

Facebook also does not recognize the New gTLDs when typed in the post. It converts the .com domains to clickable hyperlinks, whereas it does not create a link for example.technology.

More and more people from non-Latin language speaking countries are using Facebook. Yet, the new gTLDs, Internationalized Domain Names (IDNs) are not correctly recognized in Facebook.

You may update the TLD listing or automate the update by drawing the content from the DNS root zone or from https://www.iana.org/domains/root/db

Email address internationalization check can be done from https://uasg.tech/eai-check/

Quick guide for linkification: https://uasg.tech/wp-content/uploads/documents/UASG010-en-digital.pdf

Regards

**Comment by zpao** [comment]
Which library are you referring to?

If you're talking about Facebook the product, please read https://www.facebook.com/help/186570224871049 and report directly there.

**Comment by UA2018** [comment]
I already reported from there to Facebook several times for the last 1,5 years. Nothing has changed.

The library that  includes the list of valid top level domains (TLDs).

An example of that is "twitter". See https://github.com/twitter/twitter-text/blob/master/conformance/tld_lib.yml

**Comment by zpao** [comment]
This isn't related to a library inside fbjs so I'm going to close out. I'll see if there's anything to follow up on internally.
