### ISSUE TITLE
Module moved warning for react-native-community/art

### ISSUE THREAD

**Issue by piyuaryan** [facebook/fbjs#369]
Hello,
I've an expo based app. I was using expo SDK 33 so far and now I'm trying to upgrade to SDK v36.

After upgrading Expo, Typescript and Jest libraries, I'm getting this warning while running Junits.
Not sure whether it's going to warn me while app is running as well (I'm still in middle of upgrading all my libs).

Since warning is for fbjs package, I'm posting it here.

```
console.error node_modules/react-native/node_modules/fbjs/lib/warning.js:30
      Warning: React Native ART has been extracted from react-native core and w
ill be removed in a future release. It can now be installed and imported from '
@react-native-community/art' instead of 'react-native'. See https://github.com/
react-native-community/art
```

I tried to add the library manually but warning is still present. So, looks like library source code itself has to be updated.

Apologies if this is already been done. Let me know.
If this is already done then maybe I'll have to look for other npm libs in my project that uses "fbjs".

Thanks.
-
Piyush

**Comment by zpao** [comment]
`warning` is just what's being used to log, which is why it's in the stack. The actual content of the warning is not something we can help with. From the sounds of it, you're using `art` directly from react-native but shouldn't be.
