### ISSUE TITLE
Use GitHub Actions

### ISSUE THREAD

**Issue by zpao** [facebook/fbjs#382]
We should switch. For a couple reasons:
1. reduce our Travis CI queue usage
2. Actions is lightweight enough and provides easy JS tooling

@bigfootjon - want to do it since you know too much about Actions now after https://github.com/facebook/fbshipit/pull/94?

**Comment by bigfootjon** [comment]
![](https://media1.tenor.com/images/37f44b74a986e87e832b97d08bc02536/tenor.gif?itemid=12281820)
