### ISSUE TITLE
upgrade core-js version

### ISSUE THREAD

**Issue by avin-kavish** [facebook/fbjs#491]
warning evergreen-ui > glamor > fbjs > core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

**Comment by zpao** [comment]
fbjs@v0.8 isn't actively supported so I'm going to close this. Newer versions don't use core-js.
