### ISSUE TITLE
Deprecated babel plugins

### ISSUE THREAD

**Issue by strmer15** [facebook/fbjs#518]
Both `@babel/plugin-proposal-class-properties` and `@babel/plugin-proposal-object-rest-spread` are now deprecated:

https://www.npmjs.com/package/@babel/plugin-proposal-class-properties
https://www.npmjs.com/package/@babel/plugin-proposal-object-rest-spread

Instead, `babel-preset-fbjs` should be using `@babel/plugin-transform-class-properties` and `@babel/plugin-transform-object-rest-spread`.

**Comment by peter-siket-szasz** [comment]
Will the npm package be updated with the non-deprecated dependencies?

Currently the [latest release 3.4.0](https://www.npmjs.com/package/babel-preset-fbjs?activeTab=dependencies) on npm is from May 2021 and still has the deprecated dependencies.

**Comment by BabakScript** [comment]
@bigfootjon Any plan to release this fix? As @peter-siket-szasz  mentioned the latest version on NPM is back to May 2021.
