### ISSUE TITLE
Missing LICENSE file in the repo of ver 2.1.4

### ISSUE THREAD

**Issue by itsuki-murata** [facebook/fbjs#532]
Currently I'm using babel-preset-fbjs version 2.1.4, but can't find a LICENSE file in the repo of ver 2.1.4.
Could you add the LICENSE file in the repo of ver 2.1.4?
Or is it possible to use the LICENSE file of the latest version as the license for ver 2.1.4?
Thanks in advance.

**Comment by zpao** [comment]
I can't update the tag and honestly it's not practical to update and ship new versions of the code from that time period. I can safely say though that the LICENSE and related PATENTS files from that release that were at the root of the repo are accessible in this directory: https://github.com/facebook/fbjs/tree/babel-preset-fbjs-v2.1.4/packages/fbjs. This commit (and specifically the linked file move) are the evidence here. https://github.com/facebook/fbjs/commit/64208e08a409b9b4a078aa8d09a5ab3977d3b085#diff-c26dca7026772976ceeb4142731e128f9c171d9915061f5173abf65c6f807e26.

The project was subsequently relicensed to MIT.

All that said, babel-preset-fbjs was published for our own projects to use. It's obviously public but I called out from the beginning that there could be issues. It's also ancient at this point so I wouldn't recommend using it anyway.

> If you are consuming the code here and you are not also a Facebook project, be prepared for a bad time.
