### ISSUE TITLE
Inline requires throwing errors on existing node modules

### ISSUE THREAD

**Issue by nsimmons** [facebook/fbjs#58]
I noticed that the react-native CI has been failing recently. 

An example CI failure: https://travis-ci.org/facebook/react-native/jobs/81593108

It's all related to 
```
Error: /Users/travis/build/facebook/react-native/node_modules/yeoman-generator/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js: Cannot assign to a require(...) alias, debug. Line: 53
```
Seems like this started happening after react-native started using `fbjs-scripts` here: https://github.com/facebook/react-native/commit/3fca7f4d7ba7a698c9831ac4ec6ad005be453bc0

This code is throwing the error: https://github.com/facebook/fbjs/blob/76faf46086f95141fe527eee567f8bc79b23a456/scripts/babel/inline-requires.js#L74-L91

I located the source of the error being thrown and put up a PR for it here: 
https://github.com/nodejs/readable-stream/pull/161

But the question is, why do we want to throw an error here? There might be other node modules that do this kind of thing, and this error will show up every time this comes up. Fixing this error requires the source code to be fixed, the offending npm module to be published with the fix, and all npm modules that use it to get a version bump and also republished. 

Seems kind of painful to me. I don't understand the context of why we need to throw an error in this case though. 

@cpojer Could you provide some info here?

**Comment by cpojer** [comment]
We are using the `inline-require` transform for unit tests to do lazy mocking and to be able to use top-level requires in jest unit tests to be more consistent with how we write regular modules. We shouldn't be applying it to third-party code that doesn't need transforms to be applied, I'll fix the issue in react-native.

The issue is:

```js
var A = require('A');

A = Foo;
```

gets transformed to

```js
require('A') = Foo;
```

**Comment by nsimmons** [comment]
Makes sense! That would be super weird. Thanks for the explanation.

**Comment by boourns** [comment]
@cpojer I've found another case where this transform is being applied to vendored code.  Trying to run xcode integration tests in react-native 0.12 or 0.13, on circle ci results in the following from the packager:
```
{"message":"TransformError: /Users/distiller/shopify-native/node_modules/react-native/node_modules/react-tools/src/shared/vendor/performance/performanceNow.js: /Users/distiller/shopify-native/node_modules/react-native/node_modules/react-tools/src/shared/vendor/performance/performanceNow.js: Cannot assign to a require(...) alias, performance. Line: 21","type":"TransformError","errors":[{}]}
```

**Comment by cpojer** [comment]
I don't know how the xcode integration tests are being run but they need to manually ignore performanceNow for now, just like the jest preprocessor in react-native does. @balpert will be upgrading react-native to react 0.14 soon, so this issue will go away. Also cc @ide in case he knows anything about circleci setup.
