### ISSUE TITLE
Better fetch module for server-side compat

### ISSUE THREAD

**Issue by zpao** [facebook/fbjs#60]
https://github.com/facebook/relay/issues/136 has relevant discussion. The proposed module to use is https://www.npmjs.com/package/isomorphic-fetch

**Comment by taion** [comment]
@zpao 

Webpack prefers the browser version (by default), so it works just fine with `isomorphic-fetch` and properly pulls in the browser polyfill. I use this exact configuration for my non-Relay applications and it works as expected.

With RN, I believe both versions of the polyfill are set up to not replace the global version if one is already available. The risk would more be if they just completely failed to import - I can't easily test this right now; don't have an RN setup yet.

**Comment by taion** [comment]
Specifically I use `isomorphic-fetch` with Webpack in a configuration exactly analogous to the Relay case - `isomorphic-fetch` is a subdependency of a library that I directly depend on, and Webpack properly resolves the browser version.

**Comment by zpao** [comment]
Awesome, thanks for the info! Seems like it should *just work* for the majority of cases then.

> With RN, I believe both versions of the polyfill are set up to not replace the global version if one is already available.

You're right it does. Still haven't had a chance to look into the RN support. Perhaps @vjeux knows?

**Comment by vjeux** [comment]
React Native uses github's fetch implementation that takes over the global variable:
https://github.com/facebook/react-native/blob/7f76f08a11fe1354b132c2875dc2fcf6195c2979/Libraries/Fetch/fetch.js
https://github.com/facebook/react-native/blob/ce814686078058b01bbbf39017745a3ebd1ec07a/Libraries/JavaScriptAppEngine/Initialization/InitializeJavaScriptAppEngine.js#L117-L121

Happy to change it to isomorphic fetch or anything else if it still works in React Native

**Comment by taion** [comment]
@vjeux: `isomorphic-fetch` uses keys on `package.json` to plug into `node-fetch` or `whatwg-fetch`. If the RN packager pulls in the browser versions of libraries over the Node versions, then using `isomorphic-fetch` should just pull in `whatwg-fetch`. Otherwise there might be some extra work involved.

**Comment by zpao** [comment]
Talked with @vjeux in person, sounds like the packager will use the `browser` field so we should be fine. The only issue left for them is then having multiple fetch impls packaged (even if only 1 is used, there are a few extra bytes)

**Comment by taion** [comment]
Huh? Does the RN packager pull in unused files? Why would it pull in `node-fetch` at all if it's just going off what's on the `browser` field?

**Comment by zpao** [comment]
Didn't say it would. But RN already has a copy of `fetch` (linked above) so Relay's requires getting rewritten to pull in `fbjs/lib/fetch` would then bring in a 2nd copy of `whatwg-fetch`

**Comment by taion** [comment]
Got it - thanks for explaining that.

**Comment by zpao** [comment]
The comments in https://github.com/facebook/relay/issues/26 make me think this won't actually work in RN due to `self` not existing (https://github.com/matthew-andrews/isomorphic-fetch/blob/master/fetch-npm-browserify.js is exactly what we were doing)

**Comment by boourns** [comment]
@zpao that is correct.  I tried this branch with react-native and still ended up with fetch undefined.

**Comment by zpao** [comment]
I think this got worked out in another PR so going to close out. We'll revisit if we need to.
